"""Generates PDF reports for completed plagiarism scans."""
from __future__ import annotations

from pathlib import Path

from fpdf import FPDF
from sqlalchemy.orm import Session

from backend.config import settings
from backend.database.models import Document, Match, ScanHistory
from backend.utils.logger import get_logger

logger = get_logger(__name__)

_CLASSIFICATION_COLORS = {
    "Exact Copy": (220, 53, 69),
    "Near Copy": (253, 126, 20),
    "Paraphrased": (255, 193, 7),
    "Original": (40, 167, 69),
}


class ReportPDF(FPDF):
    def header(self) -> None:
        self.set_font("Helvetica", "B", 16)
        self.set_text_color(30, 30, 30)
        self.cell(0, 10, "AI Plagiarism Detection Report", ln=True, align="C")

        self.set_font("Helvetica", "", 9)
        self.set_text_color(120, 120, 120)
        self.cell(
            0,
            6,
            "Generated by the AI-Powered Plagiarism Detection System",
            ln=True,
            align="C",
        )
        self.ln(4)

    def footer(self) -> None:
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"Page {self.page_no()}", align="C")


class ReportService:
    """Creates PDF reports for plagiarism scan results."""

    def generate(self, db: Session, scan: ScanHistory) -> str:
        document = db.query(Document).filter(Document.id == scan.document_id).first()

        matches = (
            db.query(Match)
            .filter(Match.scan_id == scan.id)
            .order_by(Match.query_sentence_index.asc())
            .all()
        )

        pdf = ReportPDF()
        pdf.set_auto_page_break(auto=True, margin=18)
        pdf.add_page()

        self._write_summary(pdf, document, scan)
        self._write_breakdown_table(pdf, scan)
        self._write_matches(pdf, matches)

        report_path = Path(settings.report_dir) / f"report_{scan.id}.pdf"
        pdf.output(str(report_path))

        scan.report_path = str(report_path)
        db.add(scan)
        db.commit()

        logger.info("Generated PDF report at %s", report_path)
        return str(report_path)

    @staticmethod
    def _write_summary(
        pdf: ReportPDF,
        document: Document | None,
        scan: ScanHistory,
    ) -> None:
        pdf.set_font("Helvetica", "B", 12)
        pdf.set_text_color(0, 0, 0)

        pdf.cell(
            0,
            8,
            f"Document: {document.filename if document else scan.document_id}",
            ln=True,
        )

        pdf.set_font("Helvetica", "", 10)
        pdf.cell(0, 6, f"Scan ID: {scan.id}", ln=True)
        pdf.cell(
            0,
            6,
            f"Scanned at: {scan.created_at.strftime('%Y-%m-%d %H:%M:%S UTC')}",
            ln=True,
        )
        pdf.cell(0, 6, f"Embedding model: {scan.embedding_model}", ln=True)
        pdf.cell(0, 6, f"LLM provider: {scan.llm_provider}", ln=True)
        pdf.cell(
            0,
            6,
            f"Total sentences analyzed: {scan.total_sentences}",
            ln=True,
        )
        pdf.cell(
            0,
            6,
            f"Execution time: {scan.execution_time_seconds:.2f} seconds",
            ln=True,
        )
        pdf.ln(4)

        pdf.set_font("Helvetica", "B", 22)

        if scan.overall_plagiarism_pct >= 50:
            color = (220, 53, 69)
        elif scan.overall_plagiarism_pct >= 20:
            color = (253, 126, 20)
        else:
            color = (40, 167, 69)

        pdf.set_text_color(*color)
        pdf.cell(
            0,
            14,
            f"Overall Plagiarism: {scan.overall_plagiarism_pct:.1f}%",
            ln=True,
        )

        pdf.set_text_color(0, 0, 0)
        pdf.ln(2)

    @staticmethod
    def _write_breakdown_table(pdf: ReportPDF, scan: ScanHistory) -> None:
        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(0, 8, "Classification Breakdown", ln=True)

        rows = [
            ("Exact Copy", scan.exact_copy_pct),
            ("Near Copy", scan.near_copy_pct),
            ("Paraphrased", scan.paraphrased_pct),
            ("Original", scan.original_pct),
        ]

        pdf.set_font("Helvetica", "", 10)
        col_w = 60

        for label, pct in rows:
            color = _CLASSIFICATION_COLORS.get(label, (0, 0, 0))
            pdf.set_fill_color(*color)
            pdf.rect(pdf.get_x(), pdf.get_y() + 1, 4, 4, style="F")
            pdf.set_x(pdf.get_x() + 6)
            pdf.cell(col_w, 6, f"{label}: {pct:.1f}%", ln=True)

        pdf.ln(4)

    @staticmethod
    def _write_matches(pdf: ReportPDF, matches: list[Match]) -> None:
        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(0, 8, "Sentence-Level Matches", ln=True)
        pdf.ln(1)

        for match in matches:
            if match.classification == "Original":
                continue

            color = _CLASSIFICATION_COLORS.get(match.classification, (0, 0, 0))

            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(*color)
            pdf.set_x(pdf.l_margin)
            pdf.multi_cell(
                pdf.epw,
                6,
                f"[{match.classification}] confidence={match.confidence_score:.2f}  "
                f"similarity={match.similarity_score:.2f}",
            )

            pdf.set_text_color(0, 0, 0)

            pdf.set_font("Helvetica", "", 9)
            pdf.set_x(pdf.l_margin)
            pdf.multi_cell(0, 5, f"Query: {match.query_sentence}")

            if match.matched_text:
                pdf.set_font("Helvetica", "I", 9)
                pdf.set_x(pdf.l_margin)
                pdf.multi_cell(0, 5, f"Matched: {match.matched_text}")

            pdf.set_font("Helvetica", "", 8)

            source = match.source_document_name or "N/A"
            page = (
                match.source_page_number
                if match.source_page_number is not None
                else "N/A"
            )
            pdf.set_x(pdf.l_margin)
            pdf.multi_cell(0, 5, f"Source: {source} (page {page})")

            if match.reason:
                pdf.set_font("Helvetica", "", 8)
                pdf.set_text_color(90, 90, 90)
                pdf.set_x(pdf.l_margin)
                pdf.multi_cell(0, 5, f"Reason: {match.reason}")
                pdf.set_text_color(0, 0, 0)

            pdf.ln(3)


def get_report_service() -> ReportService:
    return ReportService()
